//! Static contracts of Android support for the `soos-remote` phone companion and Web Push
//! (GitHub #349, ADR 2026-10-09 "Android Support for the `soos-remote` Phone Companion and Web
//! Push", architect spec `AI/architect_spec_remote_android.md` §11.1; matrix RAN1–RAN11):
//!
//! - RAN-S1 every notification carries `renotify`, the raster `icon` and the monochrome
//!   `badge`; the worker makes no request on push;
//! - RAN-S2 `pushsubscriptionchange` re-sends the renewed subscription once, silently, bounded,
//!   with the page's exact request shape;
//! - RAN-S3 the manifest is installable on Android (`id`, five icons in order);
//! - RAN-S4 the four new PNG icons are well formed, bounded and generated by documented
//!   deterministic commands;
//! - RAN-S5 the four new assets are embedded and routed; the CSP is unchanged;
//! - RAN-S6 user-visible page text is platform neutral;
//! - RAN-S7 a subscription of unknown key is kept; the wait for the worker is bounded;
//! - RAN-S8 the push service classification is exhaustive and labelled;
//! - RAN-S9 Android is documented (section 2h, ADR, tester contract);
//! - RAN-S10 the installer text is platform neutral.
//!
//! The JavaScript checks are static (the project has no JS runtime in CI): comments are
//! stripped with a small lexer that keeps strings, template literals and regular expression
//! literals intact, and function bodies are scoped by brace matching outside those tokens.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    reason = "Architectural invariant test runner utilizes direct assertions, panics, and indexing"
)]

use std::fs;

use crate::remote_companion_contract::{
    exists, production_part, read, strip_comments, workspace_root,
};

const SW_JS: &str = "crates/remote/assets/sw.js";
const APP_JS: &str = "crates/remote/assets/app.js";
const INDEX: &str = "crates/remote/assets/index.html";
const MANIFEST: &str = "crates/remote/assets/manifest.webmanifest";
const ASSETS_RS: &str = "crates/remote/src/assets.rs";
const ROUTES_RS: &str = "crates/remote/src/routes.rs";
const REMOTE_LIB: &str = "crates/remote/src/lib.rs";
const HTTP_RS: &str = "crates/remote/src/http.rs";
const HTTP_TESTS: &str = "crates/remote/tests/http_tests.rs";
const PUSH_RS: &str = "crates/remote/src/push.rs";
const PROTOCOL_LIB: &str = "crates/push-protocol/src/lib.rs";
const REMOTE_DOC: &str = "Docs/REMOTE_COMPANION.md";
const DECISIONS: &str = "AI/DECISIONS.md";
const INSTALLER: &str = "scripts/install_remote.sh";
const TESTER_CONTRACT: &str = "AI/tester_contract_remote_android.md";

/// ADR title of spec §14.
const ADR_TITLE: &str = "Android Support for the `soos-remote` Phone Companion and Web Push";

/// The exact Content-Security-Policy value (spec §2.3: unchanged).
const PINNED_CSP: &str = "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; manifest-src 'self'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";

/// The platform-neutral passkey phrase (spec D-6).
const NEUTRAL_SUFFIX: &str = ", fingerprint or screen lock";

/// `(file name, width = height, color type, maximum bytes)` of the four new icons (spec §6).
const NEW_ICONS: [(&str, u32, u8, usize); 4] = [
    ("icon-192.png", 192, 2, 8 * 1024),
    ("icon-512.png", 512, 2, 16 * 1024),
    ("icon-maskable-512.png", 512, 2, 16 * 1024),
    ("badge-96.png", 96, 6, 4 * 1024),
];

/// `(AssetId variant, file name)` of the four new assets (spec §2.3).
const NEW_ASSETS: [(&str, &str); 4] = [
    ("Icon192", "icon-192.png"),
    ("Icon512", "icon-512.png"),
    ("IconMaskable512", "icon-maskable-512.png"),
    ("Badge96", "badge-96.png"),
];

/// The §4.1 constants of `app.js`, as their exact definitions (formatted as in the spec).
const APP_TEXT_CONSTANTS: [(&str, &str); 4] = [
    (
        "PASSKEY_PROMPT_TEXT",
        "\"Confirm with your passkey (Face ID, fingerprint or screen lock)\u{2026}\"",
    ),
    (
        "PUSH_UNSUPPORTED_TEXT",
        "\"On iPhone, notifications need the home-screen app (iOS 16.4 or later); this browser does not support them\"",
    ),
    (
        "PUSH_BLOCKED_TEXT",
        "\"Notifications are blocked: allow them for this site in the browser or phone settings\"",
    ),
    (
        "PUSH_WORKER_FAILED_TEXT",
        "\"Notifications could not start: the service worker did not register (reload the page and try again)\"",
    ),
];

// ---------------------------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------------------------

fn read_bytes(rel: &str) -> Vec<u8> {
    let path = workspace_root().join(rel);
    fs::read(&path).unwrap_or_else(|e| panic!("Cannot read {}: {e}", path.display()))
}

/// `text` without any whitespace.
fn no_whitespace(text: &str) -> String {
    text.chars().filter(|c| !c.is_whitespace()).collect()
}

/// Whitespace runs collapsed to one space.
fn squash(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Whether a `/` at byte `i` of `code` starts a regular expression literal (and not a
/// division): the previous non-blank byte is an operator, an opening bracket or nothing.
fn starts_regex(code: &[u8], i: usize) -> bool {
    let mut j = i;
    while j > 0 {
        j -= 1;
        let b = code[j];
        if b == b' ' || b == b'\t' || b == b'\n' || b == b'\r' {
            continue;
        }
        if b.is_ascii_alphanumeric() || b == b'_' || b == b'$' {
            let mut k = j + 1;
            while k > 0
                && (code[k - 1].is_ascii_alphanumeric()
                    || code[k - 1] == b'_'
                    || code[k - 1] == b'$')
            {
                k -= 1;
            }
            let word = &code[k..=j];
            return [
                &b"return"[..],
                b"typeof",
                b"case",
                b"in",
                b"of",
                b"void",
                b"delete",
                b"throw",
                b"yield",
                b"await",
            ]
            .contains(&word);
        }
        return matches!(
            b,
            b'(' | b','
                | b'='
                | b':'
                | b'['
                | b'!'
                | b'&'
                | b'|'
                | b'?'
                | b'{'
                | b'}'
                | b';'
                | b'+'
                | b'-'
                | b'*'
                | b'%'
                | b'<'
                | b'>'
                | b'~'
                | b'^'
        );
    }
    true
}

/// End (exclusive) of the string, template or regex literal starting at `i`.
fn literal_end(code: &[u8], i: usize) -> usize {
    let quote = code[i];
    let mut j = i + 1;
    let mut in_class = false;
    while j < code.len() {
        let b = code[j];
        if b == b'\\' {
            j += 2;
            continue;
        }
        if quote == b'/' {
            if b == b'[' {
                in_class = true;
            } else if b == b']' {
                in_class = false;
            } else if b == b'/' && !in_class {
                return j + 1;
            } else if b == b'\n' {
                return j;
            }
        } else if b == quote {
            return j + 1;
        }
        j += 1;
    }
    code.len()
}

/// JavaScript source with `//` and `/* */` comments removed; strings, template literals and
/// regular expression literals are kept verbatim.
fn strip_js_comments(src: &str) -> String {
    let code = src.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(code.len());
    let mut i = 0;
    while i < code.len() {
        let b = code[i];
        if b == b'"' || b == b'\'' || b == b'`' {
            let end = literal_end(code, i);
            out.extend_from_slice(&code[i..end]);
            i = end;
            continue;
        }
        if b == b'/' && i + 1 < code.len() && code[i + 1] == b'/' {
            while i < code.len() && code[i] != b'\n' {
                i += 1;
            }
            continue;
        }
        if b == b'/' && i + 1 < code.len() && code[i + 1] == b'*' {
            i += 2;
            while i + 1 < code.len() && !(code[i] == b'*' && code[i + 1] == b'/') {
                i += 1;
            }
            i += 2;
            continue;
        }
        if b == b'/' && starts_regex(&out, out.len()) {
            let end = literal_end(code, i);
            out.extend_from_slice(&code[i..end]);
            i = end;
            continue;
        }
        out.push(b);
        i += 1;
    }
    String::from_utf8(out).expect("UTF-8 source")
}

/// The comment-free code of a JavaScript asset.
fn js(rel: &str) -> String {
    assert!(exists(rel), "{rel} must exist");
    strip_js_comments(&read(rel))
}

/// The body (between the first `{` at or after `at` and its matching `}`) of comment-free
/// JavaScript `code`, braces inside literals ignored.
fn js_block_from(code: &str, at: usize) -> String {
    let bytes = code.as_bytes();
    let open = at
        + code[at..]
            .find('{')
            .unwrap_or_else(|| panic!("no block after byte {at}"));
    let mut depth = 0usize;
    let mut i = open;
    while i < bytes.len() {
        let b = bytes[i];
        if b == b'"' || b == b'\'' || b == b'`' || (b == b'/' && starts_regex(bytes, i)) {
            i = literal_end(bytes, i);
            continue;
        }
        if b == b'{' {
            depth += 1;
        } else if b == b'}' {
            depth -= 1;
            if depth == 0 {
                return code[open + 1..i].to_string();
            }
        }
        i += 1;
    }
    panic!("unbalanced block after byte {at}");
}

/// The body of the JavaScript function or listener whose text starts with `signature`.
fn js_body_of(code: &str, signature: &str) -> String {
    let at = code
        .find(signature)
        .unwrap_or_else(|| panic!("{signature} not found"));
    js_block_from(code, at)
}

/// Occurrences of the call `name(` not preceded by an identifier byte (`self.fetch(` counts).
fn call_count(code: &str, name: &str) -> usize {
    let needle = format!("{name}(");
    code.match_indices(&needle)
        .filter(|(at, _)| {
            *at == 0 || {
                let b = code.as_bytes()[*at - 1];
                !(b.is_ascii_alphanumeric() || b == b'_' || b == b'$')
            }
        })
        .count()
}

/// The value of the JavaScript string constant `const NAME = "value";`.
fn js_const_string(code: &str, name: &str) -> String {
    let prefix = format!("const {name} = \"");
    let at = code
        .find(&prefix)
        .unwrap_or_else(|| panic!("const {name} = \"…\"; not found"));
    let rest = &code[at + prefix.len()..];
    let end = rest.find('"').expect("closing quote");
    rest[..end].to_string()
}

/// The value of the Rust string constant `pub const NAME: &str = "value";`.
fn rust_const_string(code: &str, name: &str) -> String {
    let prefix = format!("pub const {name}: &str = \"");
    let at = code
        .find(&prefix)
        .unwrap_or_else(|| panic!("pub const {name}: &str = \"…\"; not found"));
    let rest = &code[at + prefix.len()..];
    let end = rest.find('"').expect("closing quote");
    rest[..end].to_string()
}

/// The text of the `## <number>.` section of a Markdown document (up to the next `## `,
/// without the final line break).
fn section<'a>(doc: &'a str, number: &str) -> &'a str {
    let heading = format!("\n## {number} ");
    let at = doc
        .find(&heading)
        .unwrap_or_else(|| panic!("section ## {number} not found"));
    let rest = &doc[at + 1..];
    let end = rest[3..].find("\n## ").map_or(rest.len(), |e| e + 3);
    &rest[..end]
}

/// Every `Face ID` of `text` is immediately followed by `, fingerprint or screen lock`.
fn face_id_offenders(text: &str) -> Vec<String> {
    text.match_indices("Face ID")
        .filter(|(at, _)| !text[at + "Face ID".len()..].starts_with(NEUTRAL_SUFFIX))
        .map(|(at, _)| {
            let end = (at + 60).min(text.len());
            let end = (end..=text.len())
                .find(|e| text.is_char_boundary(*e))
                .unwrap_or(text.len());
            text[at..end].replace('\n', " ")
        })
        .collect()
}

/// JSON text with the whitespace outside strings removed.
fn compact_json(text: &str) -> String {
    let mut out = String::new();
    let mut in_str = false;
    let mut escaped = false;
    for ch in text.chars() {
        if in_str {
            out.push(ch);
            if escaped {
                escaped = false;
            } else if ch == '\\' {
                escaped = true;
            } else if ch == '"' {
                in_str = false;
            }
        } else if ch == '"' {
            in_str = true;
            out.push(ch);
        } else if !ch.is_whitespace() {
            out.push(ch);
        }
    }
    out
}

/// PNG structure: IHDR fields and the ordered chunk names.
#[derive(Debug)]
struct PngInfo {
    width: u32,
    height: u32,
    depth: u8,
    color_type: u8,
    interlace: u8,
    chunks: Vec<String>,
}

fn be32(b: &[u8]) -> u32 {
    u32::from_be_bytes([b[0], b[1], b[2], b[3]])
}

fn png_info(bytes: &[u8]) -> Result<PngInfo, String> {
    const MAGIC: [u8; 8] = [0x89, b'P', b'N', b'G', 0x0D, 0x0A, 0x1A, 0x0A];
    if bytes.len() < 8 || bytes[..8] != MAGIC {
        return Err("not a PNG (signature)".to_string());
    }
    let mut chunks = Vec::new();
    let mut header: Option<(u32, u32, u8, u8, u8)> = None;
    let mut i = 8usize;
    while i < bytes.len() {
        if i + 12 > bytes.len() {
            return Err(format!("truncated chunk header at {i}"));
        }
        let len = be32(&bytes[i..i + 4]) as usize;
        let kind = String::from_utf8_lossy(&bytes[i + 4..i + 8]).to_string();
        let data_end = i + 8 + len;
        if data_end + 4 > bytes.len() {
            return Err(format!("truncated chunk {kind}"));
        }
        if kind == "IHDR" {
            if len != 13 {
                return Err("IHDR length is not 13".to_string());
            }
            let d = &bytes[i + 8..data_end];
            header = Some((be32(&d[0..4]), be32(&d[4..8]), d[8], d[9], d[12]));
        }
        chunks.push(kind);
        i = data_end + 4;
    }
    let (width, height, depth, color_type, interlace) =
        header.ok_or_else(|| "no IHDR chunk".to_string())?;
    Ok(PngInfo {
        width,
        height,
        depth,
        color_type,
        interlace,
        chunks,
    })
}

/// The CSP value of a Rust source holding `Content-Security-Policy: …\r\n` or a `CSP`
/// constant, with `\`-newline continuations and their indentation removed.
fn csp_of_rust_literal(src: &str, start_marker: &str) -> String {
    let at = src
        .find(start_marker)
        .unwrap_or_else(|| panic!("{start_marker} not found"));
    let rest = &src[at + start_marker.len()..];
    let end = ["\\r\\n", "\";"]
        .iter()
        .filter_map(|m| rest.find(m))
        .min()
        .expect("end of the CSP literal");
    let raw = &rest[..end];
    let mut out = String::new();
    let mut lines = raw.split("\\\n");
    if let Some(first) = lines.next() {
        out.push_str(first);
    }
    for line in lines {
        out.push_str(line.trim_start());
    }
    out
}

/// Self-test of the JavaScript helpers on literal snippets.
#[test]
fn test_ran_helper_js_lexer_self_test() {
    let src = "const A = \"// not a comment\"; // gone\nconst R = /\\//g; /* gone */ const B = `{`;\nfunction f(x) { if (x) { return \"}\"; } return /}/.test(x); }\n";
    let code = strip_js_comments(src);
    assert!(code.contains("\"// not a comment\""), "{code}");
    assert!(!code.contains("gone"), "{code}");
    assert!(code.contains("/\\//g"), "{code}");
    assert!(code.contains("`{`"), "{code}");
    let body = js_body_of(&code, "function f(");
    assert!(body.contains("return \"}\";"), "{body}");
    assert!(body.trim_end().ends_with("return /}/.test(x);"), "{body}");
    assert_eq!(call_count("a.fetch(x); fetch(y); prefetch(z)", "fetch"), 2);
    assert_eq!(js_const_string("const P = \"/x\";", "P"), "/x");
    assert_eq!(
        face_id_offenders("Face ID, fingerprint or screen lock and Face ID alone").len(),
        1
    );
    let doc = "intro\n## 2g. G\ng text\n## 2h. H\nh text\n## 3. Next\n";
    assert_eq!(section(doc, "2h."), "## 2h. H\nh text");
    assert_eq!(
        csp_of_rust_literal(
            "const CSP: &str = \"default-src 'self'; \\\n                   img-src 'self'\";",
            "const CSP: &str = \""
        ),
        "default-src 'self'; img-src 'self'"
    );
}

// ---------------------------------------------------------------------------------------------
// RAN-S1
// ---------------------------------------------------------------------------------------------

/// RAN-S1 (RAN1, spec §3.1): `renotify`, the raster icon and the monochrome badge on every
/// notification; the `push` path of the worker issues no request and stores nothing.
#[test]
fn test_ran_s1_service_worker_notification_options() {
    let code = js(SW_JS);
    for needle in [
        "const ICON_PATH = \"/icon-192.png\";",
        "const BADGE_PATH = \"/badge-96.png\";",
    ] {
        assert!(code.contains(needle), "sw.js must contain {needle}");
    }
    assert_eq!(
        code.matches("addEventListener(\"push\"").count(),
        1,
        "one push listener"
    );
    let push = js_body_of(&code, "addEventListener(\"push\"");
    assert!(
        push.contains("event.waitUntil(") && push.contains("showNotification("),
        "every push shows a notification inside waitUntil"
    );
    let options = js_block_from(
        &push,
        push.find("showNotification(").expect("showNotification"),
    );
    for needle in [
        "renotify: true",
        "icon: ICON_PATH",
        "badge: BADGE_PATH",
        "tag: shown.tag",
        "body: shown.body",
    ] {
        assert!(
            options.contains(needle),
            "the push notification options must contain {needle}: {options}"
        );
    }
    let read_notification = js_body_of(&code, "function readNotification(");
    for (name, body) in [
        ("push listener", &push),
        ("readNotification", &read_notification),
    ] {
        assert_eq!(call_count(body, "fetch"), 0, "{name} must not call fetch(");
        assert!(!body.contains("caches"), "{name} must not use caches");
    }
    for forbidden in [
        "addEventListener(\"fetch\"",
        "importScripts",
        "caches",
        "localStorage",
        "indexedDB",
        "http://",
        "https://",
        "eval(",
        "innerHTML",
        "Function(",
        "setInterval",
    ] {
        assert!(
            !code.contains(forbidden),
            "sw.js must not contain {forbidden}"
        );
    }
}

// ---------------------------------------------------------------------------------------------
// RAN-S2
// ---------------------------------------------------------------------------------------------

/// RAN-S2 (RAN2, spec §3.2, §3.3, §9): one silent, bounded re-subscription request with the
/// page's exact request shape, the same key, and the server's constants.
#[test]
fn test_ran_s2_service_worker_resubscribes_once_with_the_page_request_shape() {
    let code = js(SW_JS);
    assert_eq!(
        code.matches("addEventListener(\"pushsubscriptionchange\"")
            .count(),
        1,
        "exactly one pushsubscriptionchange listener"
    );
    let listener = js_body_of(&code, "addEventListener(\"pushsubscriptionchange\"");
    assert!(
        listener.trim_start().starts_with("event.waitUntil("),
        "the listener is wrapped in event.waitUntil(: {listener}"
    );
    let squashed = squash(&listener);
    let catch_at = squashed
        .rfind(".catch(() => null)")
        .unwrap_or_else(|| panic!("the listener ends with .catch(() => null): {squashed}"));
    let tail = &squashed[catch_at + ".catch(() => null)".len()..];
    assert!(
        tail.chars().all(|c| c == ')' || c == ';' || c == ' '),
        "the .catch(() => null) is terminal: {squashed}"
    );
    assert!(
        listener.contains("renewedSubscription(event)") && listener.contains("postSubscription("),
        "the listener chains renewedSubscription(event) and postSubscription(: {listener}"
    );

    assert_eq!(call_count(&code, "fetch"), 1, "exactly one fetch( in sw.js");
    let post = js_body_of(&code, "function postSubscription(");
    assert_eq!(
        call_count(&post, "fetch"),
        1,
        "the single fetch( is in postSubscription"
    );
    for needle in [
        "fetch(SUBSCRIBE_PATH,",
        "method: \"POST\"",
        "\"X-Soos-Action\": SUBSCRIBE_ACTION",
        "\"Content-Type\": \"application/json\"",
        "JSON.stringify(subscription.toJSON())",
        "credentials: \"same-origin\"",
        "cache: \"no-store\"",
        "signal: controller.signal",
        "new AbortController()",
        "setTimeout(",
        "RESUBSCRIBE_TIMEOUT_MS",
        "clearTimeout(timer)",
    ] {
        assert!(
            post.contains(needle),
            "postSubscription must contain {needle}: {post}"
        );
    }
    let headers = js_block_from(&post, post.find("headers:").expect("headers:"));
    assert_eq!(
        squash(&headers),
        "\"X-Soos-Action\": SUBSCRIBE_ACTION, \"Content-Type\": \"application/json\"",
        "no other header than the page's two"
    );
    assert!(
        code.contains("const RESUBSCRIBE_TIMEOUT_MS = 10000;"),
        "const RESUBSCRIBE_TIMEOUT_MS = 10000;"
    );

    let routes = strip_comments(production_part(&read(ROUTES_RS)));
    let lib = strip_comments(production_part(&read(REMOTE_LIB)));
    assert_eq!(
        js_const_string(&code, "SUBSCRIBE_PATH"),
        rust_const_string(&routes, "PUSH_SUBSCRIBE_PATH"),
        "SUBSCRIBE_PATH equals PUSH_SUBSCRIBE_PATH of routes.rs"
    );
    assert_eq!(
        js_const_string(&code, "SUBSCRIBE_PATH"),
        "/api/push/subscribe"
    );
    assert_eq!(
        js_const_string(&code, "SUBSCRIBE_ACTION"),
        rust_const_string(&lib, "ACTION_PUSH_SUBSCRIBE"),
        "SUBSCRIBE_ACTION equals ACTION_PUSH_SUBSCRIBE of lib.rs"
    );
    assert_eq!(js_const_string(&code, "SUBSCRIBE_ACTION"), "push-subscribe");

    let renewed = js_body_of(&code, "function renewedSubscription(");
    for needle in [
        "event.newSubscription",
        "event.oldSubscription",
        ".options.applicationServerKey",
        "pushManager.subscribe(",
        "userVisibleOnly: true",
        "applicationServerKey: key",
        "Promise.resolve(null)",
    ] {
        assert!(
            renewed.contains(needle),
            "renewedSubscription must contain {needle}: {renewed}"
        );
    }
    assert_eq!(
        call_count(&renewed, "fetch"),
        0,
        "renewedSubscription never fetches"
    );
    for (name, body) in [
        ("renewedSubscription", &renewed),
        ("postSubscription", &post),
    ] {
        for forbidden in ["while (", "for (", "setInterval", "showNotification"] {
            assert!(
                !body.contains(forbidden),
                "{name} must not contain {forbidden}"
            );
        }
    }
    for forbidden in [".then(", ".json()", ".status", ".ok", ".text()"] {
        assert!(
            !post.contains(forbidden),
            "postSubscription ignores the response (no {forbidden}): {post}"
        );
    }
    for forbidden in [
        "\"/api/push\"",
        "'/api/push'",
        ".unsubscribe(",
        "setInterval",
        "localStorage",
        "indexedDB",
        "caches",
    ] {
        assert!(
            !code.contains(forbidden),
            "sw.js must not contain {forbidden}"
        );
    }
}

// ---------------------------------------------------------------------------------------------
// RAN-S3
// ---------------------------------------------------------------------------------------------

/// RAN-S3 (RAN3, spec §5): manifest `id` and exactly five icons, in order, each with exactly
/// the listed members; the iOS touch icon link is kept.
#[test]
fn test_ran_s3_manifest_is_installable_on_android() {
    let manifest = compact_json(&read(MANIFEST));
    assert!(manifest.contains(r#""id":"/""#), "manifest id \"/\"");
    assert!(!manifest.contains("http"), "manifest has no absolute URL");
    let icons_at = manifest.find(r#""icons":["#).expect("icons array") + r#""icons":["#.len();
    let icons_end = icons_at + manifest[icons_at..].find(']').expect("]");
    let objects: Vec<Vec<String>> = manifest[icons_at..icons_end]
        .split("},")
        .map(|o| {
            let inner = o.trim_start_matches('{').trim_end_matches('}');
            let mut members: Vec<String> = inner.split(',').map(str::to_string).collect();
            members.sort();
            members
        })
        .collect();
    let expected: [&[&str]; 5] = [
        &[
            r#""src":"icon.svg""#,
            r#""sizes":"any""#,
            r#""type":"image/svg+xml""#,
        ],
        &[
            r#""src":"apple-touch-icon.png""#,
            r#""sizes":"180x180""#,
            r#""type":"image/png""#,
        ],
        &[
            r#""src":"icon-192.png""#,
            r#""sizes":"192x192""#,
            r#""type":"image/png""#,
            r#""purpose":"any""#,
        ],
        &[
            r#""src":"icon-512.png""#,
            r#""sizes":"512x512""#,
            r#""type":"image/png""#,
            r#""purpose":"any""#,
        ],
        &[
            r#""src":"icon-maskable-512.png""#,
            r#""sizes":"512x512""#,
            r#""type":"image/png""#,
            r#""purpose":"maskable""#,
        ],
    ];
    let expected: Vec<Vec<String>> = expected
        .iter()
        .map(|members| {
            let mut v: Vec<String> = members.iter().map(|m| (*m).to_string()).collect();
            v.sort();
            v
        })
        .collect();
    assert_eq!(
        objects, expected,
        "exactly the five icons of spec §5, in order"
    );
    let index = read(INDEX);
    assert!(
        index.contains(r#"<link rel="apple-touch-icon" href="apple-touch-icon.png">"#),
        "index.html keeps the apple-touch-icon link"
    );
}

// ---------------------------------------------------------------------------------------------
// RAN-S4
// ---------------------------------------------------------------------------------------------

/// RAN-S4 (RAN4, spec §6): the four new PNGs are well formed and bounded; their generation
/// commands are documented in section 2e.
#[test]
fn test_ran_s4_android_icons_are_well_formed_pngs() {
    for (file, side, color_type, max_bytes) in NEW_ICONS {
        let rel = format!("crates/remote/assets/{file}");
        assert!(exists(&rel), "{rel} must exist (spec §6)");
        let bytes = read_bytes(&rel);
        assert!(
            bytes.len() <= max_bytes,
            "{file}: {} bytes > {max_bytes}",
            bytes.len()
        );
        let info = png_info(&bytes).unwrap_or_else(|e| panic!("{file}: {e}"));
        assert_eq!((info.width, info.height), (side, side), "{file} size");
        assert_eq!(info.depth, 8, "{file} bit depth");
        assert_eq!(info.color_type, color_type, "{file} color type");
        assert_eq!(info.interlace, 0, "{file} is not interlaced");
        let n = info.chunks.len();
        assert!(n >= 3, "{file}: {:?}", info.chunks);
        assert_eq!(info.chunks[0], "IHDR", "{file}: {:?}", info.chunks);
        assert_eq!(info.chunks[n - 1], "IEND", "{file}: {:?}", info.chunks);
        assert!(
            info.chunks[1..n - 1].iter().all(|c| c == "IDAT"),
            "{file}: chunks exactly IHDR, IDAT+, IEND: {:?}",
            info.chunks
        );
    }
    let doc = read(REMOTE_DOC);
    let design = squash(section(&doc, "2e."));
    for (_, file) in NEW_ASSETS {
        assert!(design.contains(file), "section 2e names {file}");
    }
    for needle in [
        "-w 408 -h 408",
        "xc:#0047BB",
        "-gravity center -composite",
        "-alpha shape",
        "png:color-type=6",
        "png:color-type=2",
        "exclude-chunks=date,time,tIME",
        "safe zone",
        "`id`",
    ] {
        assert!(design.contains(needle), "section 2e must contain {needle}");
    }
}

// ---------------------------------------------------------------------------------------------
// RAN-S5
// ---------------------------------------------------------------------------------------------

/// RAN-S5 (RAN5, spec §2.3): the four assets are embedded as `image/png` and routed by their
/// exact paths; the CSP literal is byte-identical to the pinned one.
#[test]
fn test_ran_s5_android_assets_are_embedded_and_routed() {
    let assets = strip_comments(production_part(&read(ASSETS_RS)));
    let enum_body = {
        let at = assets.find("pub enum AssetId").expect("pub enum AssetId");
        let open = at + assets[at..].find('{').expect("{");
        let close = open + assets[open..].find('}').expect("}");
        assets[open + 1..close].to_string()
    };
    for (variant, file) in NEW_ASSETS {
        assert!(
            enum_body.contains(&format!("{variant},")),
            "AssetId has the variant {variant}"
        );
        let arm_head = format!("AssetId::{variant} =>");
        let at = assets
            .find(&arm_head)
            .unwrap_or_else(|| panic!("asset() has the arm {arm_head}"));
        let arm = &assets[at + arm_head.len()..];
        let arm = &arm[..arm.find("AssetId::").unwrap_or(arm.len())];
        assert!(
            arm.contains("content_type: \"image/png\""),
            "{variant} is image/png: {arm}"
        );
        assert!(
            arm.contains(&format!("include_bytes!(\"../assets/{file}\")")),
            "{variant} embeds {file}: {arm}"
        );
    }
    let routes = strip_comments(production_part(&read(ROUTES_RS)));
    let route_body = {
        let at = routes.find("pub fn route(").expect("pub fn route(");
        let open = at + routes[at..].find('{').expect("{");
        let mut depth = 0usize;
        let mut end = open;
        for (i, c) in routes[open..].char_indices() {
            match c {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = open + i;
                        break;
                    }
                }
                _ => {}
            }
        }
        routes[open..end].to_string()
    };
    for (variant, file) in NEW_ASSETS {
        let arm = format!("\"/{file}\" => Some(Route::Asset(AssetId::{variant})),");
        assert!(
            route_body.contains(&arm),
            "route() maps the read route {arm}"
        );
    }
    let http = read(HTTP_RS);
    let served = csp_of_rust_literal(&http, "Content-Security-Policy: ");
    assert_eq!(served, PINNED_CSP, "http.rs CSP unchanged");
    let pinned = csp_of_rust_literal(&read(HTTP_TESTS), "const CSP: &str = \"");
    assert_eq!(
        served, pinned,
        "http.rs CSP equals the pinned http_tests.rs CSP"
    );
    for forbidden in ["worker-src", "blob:", "data:"] {
        assert!(
            !served.contains(forbidden),
            "CSP must not contain {forbidden}"
        );
    }
}

// ---------------------------------------------------------------------------------------------
// RAN-S6
// ---------------------------------------------------------------------------------------------

/// RAN-S6 (RAN6, spec §4.1, D-6): platform-neutral user text in the page.
#[test]
fn test_ran_s6_user_text_is_platform_neutral() {
    let app = read(APP_JS);
    let index = read(INDEX);
    for (name, text) in [("app.js", &app), ("index.html", &index)] {
        let offenders = face_id_offenders(text);
        assert!(
            offenders.is_empty(),
            "{name}: every Face ID is followed by \"{NEUTRAL_SUFFIX}\": {offenders:?}"
        );
        for forbidden in ["Touch ID", "iPhone settings", "Passwords app"] {
            assert!(
                !text.contains(forbidden),
                "{name} must not contain {forbidden}"
            );
        }
    }
    let code = strip_js_comments(&app);
    for (name, value) in APP_TEXT_CONSTANTS {
        let definition = squash(&format!("const {name} = {value};"));
        assert!(
            squash(&code).contains(&definition),
            "app.js must define {definition}"
        );
        assert_eq!(
            code.matches(&format!("const {name} =")).count(),
            1,
            "{name} is defined once"
        );
    }
    let prompt_uses = code
        .matches("PASSKEY_PROMPT_TEXT")
        .count()
        .saturating_sub(1);
    assert!(
        prompt_uses >= 4,
        "PASSKEY_PROMPT_TEXT is used by login, enroll, unlock and camera ({prompt_uses} uses)"
    );
    for needle in [
        "\"A passkey check (Face ID, fingerprint or screen lock) is required for every unlock\"",
        "from the phone's password manager",
    ] {
        assert!(code.contains(needle), "app.js must contain {needle}");
    }
    for old in [
        "Confirm with Face ID",
        "\"Notifications need the home-screen app (iOS 16.4 or later)\"",
    ] {
        assert!(!code.contains(old), "app.js must no longer contain {old}");
    }
    assert!(
        index.contains(
            r#"<button id="login-button" type="button">Sign in with your passkey</button>"#
        ),
        "index.html login button reads Sign in with your passkey"
    );
}

// ---------------------------------------------------------------------------------------------
// RAN-S7
// ---------------------------------------------------------------------------------------------

/// RAN-S7 (RAN7, spec §4.2, §4.3): `serverKeyMatch` tri-state, only a different key
/// unsubscribes, and the wait for an active service worker is bounded.
#[test]
fn test_ran_s7_push_client_keeps_unknown_key_subscriptions_and_bounds_the_worker_wait() {
    let code = js(APP_JS);
    assert!(!code.contains("sameServerKey"), "sameServerKey is replaced");
    let matcher = js_body_of(&code, "function serverKeyMatch(");
    let unknown = matcher
        .find("return \"unknown\"")
        .expect("serverKeyMatch returns \"unknown\"");
    assert!(
        matcher[..unknown].contains("applicationServerKey"),
        "\"unknown\" is decided on applicationServerKey: {matcher}"
    );
    let compare = matcher
        .find("new Uint8Array(")
        .expect("serverKeyMatch compares bytes");
    assert!(unknown < compare, "\"unknown\" before any byte comparison");
    for needle in ["return \"different\"", "return \"same\""] {
        assert!(
            matcher.contains(needle),
            "serverKeyMatch must contain {needle}"
        );
    }

    let sync = js_body_of(&code, "function syncSubscription(");
    assert!(
        sync.contains("serverKeyMatch("),
        "syncSubscription calls serverKeyMatch"
    );
    assert!(
        sync.contains("postJson(PUSH_SUBSCRIBE_PATH, \"push-subscribe\", subscription.toJSON())"),
        "same or unknown key: the subscription is re-sent"
    );
    assert_eq!(
        sync.matches(".unsubscribe(").count(),
        1,
        "one unsubscribe in syncSubscription"
    );
    let different = sync
        .find("=== \"different\"")
        .expect("syncSubscription tests === \"different\"");
    let guarded = js_block_from(&sync, different);
    assert!(
        guarded.contains(".unsubscribe("),
        "unsubscribe() only under === \"different\": {sync}"
    );
    assert!(
        guarded.contains("Notifications must be re-enabled on this phone"),
        "the re-enable text is kept"
    );

    assert!(
        code.contains("const SERVICE_WORKER_READY_TIMEOUT_MS = 10000;"),
        "const SERVICE_WORKER_READY_TIMEOUT_MS = 10000;"
    );
    assert_eq!(
        code.matches("navigator.serviceWorker.ready").count(),
        1,
        "navigator.serviceWorker.ready occurs once"
    );
    let ready = js_body_of(&code, "function readyRegistration(");
    for needle in [
        "navigator.serviceWorker.ready",
        "setTimeout(",
        "clearTimeout(",
        "SERVICE_WORKER_READY_TIMEOUT_MS",
        "resolve(null)",
        "registerServiceWorker()",
    ] {
        assert!(
            ready.contains(needle),
            "readyRegistration must contain {needle}"
        );
    }
    let enable = js_body_of(&code, "async function enableNotifications(");
    let first_await = enable.find("await").expect("enableNotifications awaits");
    assert!(
        enable[first_await + "await".len()..]
            .trim_start()
            .starts_with("Notification.requestPermission("),
        "the first await is still Notification.requestPermission()"
    );
    for needle in [
        "await readyRegistration()",
        "PUSH_WORKER_FAILED_TEXT",
        "PUSH_BLOCKED_TEXT",
        "PUSH_UNSUPPORTED_TEXT",
    ] {
        assert!(
            enable.contains(needle),
            "enableNotifications must contain {needle}"
        );
    }
    assert!(
        !enable.contains("serviceWorker.ready"),
        "enableNotifications never awaits serviceWorker.ready directly"
    );
    let at_ready = enable.find("await readyRegistration()").unwrap();
    let at_failed = enable.find("PUSH_WORKER_FAILED_TEXT").unwrap();
    let at_subscribe = enable
        .find("pushManager.subscribe(")
        .expect("enableNotifications subscribes");
    assert!(
        at_ready < at_failed && at_failed < at_subscribe,
        "a null registration ends the tap with PUSH_WORKER_FAILED_TEXT before subscribing"
    );
    assert!(
        enable[at_ready..at_failed].contains("=== null"),
        "the registration is checked against null"
    );
    assert!(enable.contains("finally"), "the finally block is kept");
}

// ---------------------------------------------------------------------------------------------
// RAN-S8
// ---------------------------------------------------------------------------------------------

/// RAN-S8 (RAN8, spec §2.1, §2.2, §4.4): `PushHost` is the single source of the allowlist,
/// `PushService::of` is exhaustive without a fallback arm, and the device labels.
#[test]
fn test_ran_s8_push_service_classification_is_exhaustive() {
    let protocol = strip_comments(production_part(&read(PROTOCOL_LIB)));
    assert!(protocol.contains("pub enum PushHost"), "pub enum PushHost");
    let flat = no_whitespace(&protocol);
    assert!(
        flat.contains(
            "pubconstALL:[PushHost;3]=[PushHost::Apple,PushHost::Google,PushHost::Mozilla];"
        ),
        "PushHost::ALL in the PUSH_HOSTS order"
    );
    assert!(
        flat.contains(
            "pubconstPUSH_HOSTS:[&str;3]=[PushHost::Apple.name(),PushHost::Google.name(),PushHost::Mozilla.name()"
        ),
        "PUSH_HOSTS is derived from PushHost::name"
    );
    for (variant, host) in [
        ("Apple", "web.push.apple.com"),
        ("Google", "fcm.googleapis.com"),
        ("Mozilla", "updates.push.services.mozilla.com"),
    ] {
        assert!(
            flat.contains(&format!("PushHost::{variant}=>\"{host}\"")),
            "PushHost::name maps {variant} to {host}"
        );
    }
    let parse = {
        let at = protocol.find("pub fn parse(").expect("pub fn parse(");
        let end = protocol[at..]
            .find("pub fn as_str(")
            .map_or(protocol.len(), |e| at + e);
        protocol[at..end].to_string()
    };
    assert!(parse.contains("PushHost::ALL"), "parse uses PushHost::ALL");
    assert!(
        !parse.contains("PUSH_HOSTS"),
        "parse no longer scans PUSH_HOSTS"
    );
    assert!(
        protocol.contains("pub fn push_host(&self) -> PushHost"),
        "PushEndpoint::push_host"
    );

    let push = strip_comments(production_part(&read(PUSH_RS)));
    let at = push
        .find("impl PushService {")
        .expect("impl PushService block");
    let block = {
        let open = at + "impl PushService ".len();
        let mut depth = 0usize;
        let mut end = open;
        for (i, c) in push[open..].char_indices() {
            match c {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = open + i;
                        break;
                    }
                }
                _ => {}
            }
        }
        push[open..=end].to_string()
    };
    for needle in [
        "pub fn of(endpoint: &PushEndpoint) -> Self",
        "endpoint.push_host()",
        "PushHost::Apple => Self::Apple",
        "PushHost::Google => Self::Google",
        "PushHost::Mozilla => Self::Mozilla",
    ] {
        assert!(
            block.contains(needle),
            "impl PushService must contain {needle}"
        );
    }
    for forbidden in [
        "_ =>",
        "\"web.push.apple.com\"",
        "\"fcm.googleapis.com\"",
        "\"updates.push.services.mozilla.com\"",
        ".host()",
    ] {
        assert!(
            !block.contains(forbidden),
            "impl PushService must not contain {forbidden}"
        );
    }

    let app = js(APP_JS);
    let services = js_body_of(&app, "const PUSH_SERVICES =");
    assert_eq!(
        squash(&services),
        "apple: \"Apple\", google: \"Android / Chrome (Google)\", mozilla: \"Firefox (Mozilla)\",",
        "PUSH_SERVICES labels of spec §4.4"
    );
}

// ---------------------------------------------------------------------------------------------
// RAN-S9
// ---------------------------------------------------------------------------------------------

/// RAN-S9 (RAN11, spec §7.1, §14): section 2h documents Android; §2d, §6, §9 updated; the
/// ADR and the tester contract exist.
#[test]
fn test_ran_s9_android_is_documented() {
    let doc = read(REMOTE_DOC);
    let g = doc.find("\n## 2g. ").expect("## 2g.");
    let h = doc.find("\n## 2h. ").expect("## 2h. Android section");
    let three = doc.find("\n## 3. ").expect("## 3.");
    assert!(g < h && h < three, "## 2h. sits between ## 2g. and ## 3.");
    let android = squash(section(&doc, "2h."));
    assert!(android.contains("Android"), "section 2h is about Android");
    for needle in [
        "Tailscale",
        "Install app",
        "Android 13",
        "Google Password Manager",
        "fingerprint",
        "screen lock",
        "Unrestricted",
        "Firefox",
        "Samsung Internet",
        "fcm.googleapis.com",
        "updates.push.services.mozilla.com",
        "pushsubscriptionchange",
        "Tasker",
        "RAN12",
        "Android / Chrome (Google)",
        "Firefox (Mozilla)",
    ] {
        assert!(android.contains(needle), "section 2h must contain {needle}");
    }
    let push = squash(section(&doc, "2d."));
    for needle in [
        "Android",
        "fcm.googleapis.com",
        "updates.push.services.mozilla.com",
        "home-screen",
        "16.4",
        "web.push.apple.com",
    ] {
        assert!(push.contains(needle), "section 2d must contain {needle}");
    }
    let surface = section(&doc, "6.");
    for (_, file) in NEW_ASSETS {
        assert!(
            surface.contains(&format!("/{file}")),
            "section 6 lists /{file}"
        );
    }
    let out_of_scope = squash(section(&doc, "9."));
    for needle in ["native Android app", "notify.windows.com", "Tasker"] {
        assert!(
            out_of_scope.contains(needle),
            "section 9 must contain {needle}"
        );
    }
    assert!(
        read(DECISIONS).contains(ADR_TITLE),
        "AI/DECISIONS.md records the ADR {ADR_TITLE}"
    );
    assert!(exists(TESTER_CONTRACT), "{TESTER_CONTRACT} exists");
}

// ---------------------------------------------------------------------------------------------
// RAN-S10
// ---------------------------------------------------------------------------------------------

/// RAN-S10 (RAN6, spec §7.2): the installer text is platform neutral.
#[test]
fn test_ran_s10_installer_text_is_platform_neutral() {
    let installer = read(INSTALLER);
    for forbidden in ["iPhone lock screen", "register Face ID", "Touch ID"] {
        assert!(
            !installer.contains(forbidden),
            "{INSTALLER} must not contain {forbidden}"
        );
    }
    let offenders = face_id_offenders(&installer);
    assert!(
        offenders.is_empty(),
        "{INSTALLER}: every Face ID is followed by \"{NEUTRAL_SUFFIX}\": {offenders:?}"
    );
    for needle in [
        "register the phone's passkey over the tailnet",
        "(the home-screen app on iPhone)",
        "# Passkeys (Face ID, fingerprint or screen lock) and internet access through Tailscale Funnel",
        "a fresh passkey check per view",
        "What the phone lock screen shows",
        "Android: section 2h",
    ] {
        assert!(installer.contains(needle), "{INSTALLER} must contain {needle}");
    }
}
