//! Upstream-parity PAD context crop geometry (review finding PAD-08, GitHub #213).
//!
//! The Silent-Face-Anti-Spoofing models were trained on crops produced by
//! `CropImage._get_new_box` (inclusive `src - 1` bounds, scale capped by `(src - 1) / box`,
//! `int()` truncation, inclusive slice) followed by `cv2.resize(INTER_LINEAR)` (half-pixel
//! centre sampling). These tests pin `pad_crop_window` and `crop_pad_context` to that
//! reference, including a committed golden fixture generated by
//! `tests/fixtures/pad_crop/generate_golden.py`.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    clippy::cast_possible_truncation,
    clippy::cast_sign_loss,
    clippy::cast_precision_loss,
    reason = "Contractual test suite uses assertions, unwrap and pixel indexing"
)]

use soos_inference_ort::BoundingBox;
use soos_vision::crop::{crop_pad_context, pad_crop_window, PadCropWindow};
use soos_vision::VisionError;

const FRAME_W: u32 = 160;
const FRAME_H: u32 = 120;

/// Same formula as `synthetic_frame()` in `generate_golden.py` (non-biometric).
fn synthetic_frame() -> Vec<u8> {
    let mut rgb = Vec::with_capacity((FRAME_W * FRAME_H * 3) as usize);
    for y in 0..FRAME_H {
        for x in 0..FRAME_W {
            rgb.push(((x * 7 + y * 3) & 0xFF) as u8);
            rgb.push((((x ^ y) * 5) & 0xFF) as u8);
            rgb.push(((x * y) & 0xFF) as u8);
        }
    }
    rgb
}

fn assert_within_one_lsb(name: &str, actual: &[u8], golden: &[u8]) {
    assert_eq!(actual.len(), golden.len(), "{name}: length mismatch");
    let mut worst = 0u8;
    let mut worst_at = 0usize;
    for (i, (&a, &g)) in actual.iter().zip(golden.iter()).enumerate() {
        let d = a.abs_diff(g);
        if d > worst {
            worst = d;
            worst_at = i;
        }
    }
    assert!(
        worst <= 1,
        "{name}: byte {worst_at} differs by {worst} LSB from the upstream reference \
         (actual {}, golden {})",
        actual[worst_at],
        golden[worst_at]
    );
}

#[test]
fn test_pad_crop_window_interior_matches_upstream_get_new_box() {
    // 100x100 face, centre (150, 150): upstream left/right = int(15.0) / int(285.0), inclusive.
    let bbox = BoundingBox::new(100.0, 100.0, 200.0, 200.0);
    let window = pad_crop_window(&bbox, 2.7, 640, 480).expect("non-degenerate window");
    assert_eq!(
        window,
        PadCropWindow {
            x: 15,
            y: 15,
            width: 271,
            height: 271
        },
        "inclusive slice img[15:286, 15:286] as in CropImage.crop"
    );
}

#[test]
fn test_pad_crop_window_shifts_inward_against_last_pixel_index() {
    // Upstream shifts against src_w - 1 = 639 and src_h - 1 = 479 (inclusive), not 640 / 480.
    let bbox = BoundingBox::new(550.0, 400.0, 630.0, 470.0);
    let window = pad_crop_window(&bbox, 2.7, 640, 480).expect("non-degenerate window");
    assert_eq!(
        window,
        PadCropWindow {
            x: 423,
            y: 290,
            width: 217,
            height: 190
        }
    );
    assert_eq!(window.x + window.width, 640, "last column is 639");
    assert_eq!(window.y + window.height, 480, "last row is 479");
}

#[test]
fn test_pad_crop_window_caps_scale_by_last_pixel_index() {
    // scale = min((480 - 1) / 300, (640 - 1) / 400, 4.0) = 479 / 300 (not 480 / 300 = 1.6):
    // new box 638.67 x 479 centred on (200, 150), shifted to x 0..=638, y 0..=479.
    let bbox = BoundingBox::new(0.0, 0.0, 400.0, 300.0);
    let window = pad_crop_window(&bbox, 4.0, 640, 480).expect("non-degenerate window");
    assert_eq!(
        window,
        PadCropWindow {
            x: 0,
            y: 0,
            width: 639,
            height: 480
        }
    );
}

#[test]
fn test_pad_crop_window_rejects_degenerate_inputs() {
    assert_eq!(
        pad_crop_window(&BoundingBox::new(10.0, 10.0, 10.0, 50.0), 2.7, 640, 480),
        None
    );
    assert_eq!(
        pad_crop_window(&BoundingBox::new(10.0, 50.0, 60.0, 50.0), 2.7, 640, 480),
        None
    );
    assert_eq!(
        pad_crop_window(&BoundingBox::new(f32::NAN, 0.0, 10.0, 10.0), 2.7, 640, 480),
        None
    );
    assert_eq!(
        pad_crop_window(
            &BoundingBox::new(0.0, 0.0, f32::INFINITY, 10.0),
            2.7,
            640,
            480
        ),
        None
    );
    assert_eq!(
        pad_crop_window(&BoundingBox::new(10.0, 10.0, 50.0, 50.0), 2.7, 0, 480),
        None
    );
    assert_eq!(
        pad_crop_window(
            &BoundingBox::new(10.0, 10.0, 50.0, 50.0),
            f32::NAN,
            640,
            480
        ),
        None
    );
}

#[test]
fn test_pad_crop_window_always_inside_frame() {
    let boxes = [
        BoundingBox::new(-50.0, -40.0, 30.0, 20.0),
        BoundingBox::new(600.0, 450.0, 700.0, 520.0),
        BoundingBox::new(0.0, 0.0, 640.0, 480.0),
        BoundingBox::new(319.5, 239.5, 320.5, 240.5),
    ];
    for bbox in boxes {
        for scale in [1.0f32, 2.7, 4.0, 100.0] {
            let w = pad_crop_window(&bbox, scale, 640, 480).expect("window");
            assert!(w.width >= 1 && w.height >= 1, "{bbox:?} @ {scale}: {w:?}");
            assert!(w.x + w.width <= 640, "{bbox:?} @ {scale}: {w:?}");
            assert!(w.y + w.height <= 480, "{bbox:?} @ {scale}: {w:?}");
        }
    }
}

#[test]
fn test_crop_pad_context_uses_half_pixel_centre_sampling() {
    // Horizontal ramp R = x: bilinear interpolation of a linear signal is exact, so the
    // cv2 INTER_LINEAR output is R(u) = window.x + clamp((u + 0.5) * W / 80 - 0.5, 0, W - 1).
    let (w, h) = (200u32, 200u32);
    let mut rgb = vec![0u8; (w * h * 3) as usize];
    for y in 0..h {
        for x in 0..w {
            let i = ((y * w + x) * 3) as usize;
            rgb[i] = x as u8;
            rgb[i + 1] = y as u8;
            rgb[i + 2] = 77;
        }
    }
    let bbox = BoundingBox::new(60.0, 60.0, 110.0, 110.0);
    let window = pad_crop_window(&bbox, 2.7, w, h).expect("window");
    let crop = crop_pad_context(&rgb, w, h, &bbox, 2.7, 80, 80).expect("crop");
    assert_eq!(crop.len(), 80 * 80 * 3);

    let scale_x = window.width as f64 / 80.0;
    let scale_y = window.height as f64 / 80.0;
    for v in 0..80u32 {
        for u in 0..80u32 {
            let fx = ((u as f64 + 0.5) * scale_x - 0.5).clamp(0.0, (window.width - 1) as f64);
            let fy = ((v as f64 + 0.5) * scale_y - 0.5).clamp(0.0, (window.height - 1) as f64);
            let expected_r = window.x as f64 + fx;
            let expected_g = window.y as f64 + fy;
            let i = ((v * 80 + u) * 3) as usize;
            assert!(
                (crop[i] as f64 - expected_r).abs() <= 1.0,
                "R({u},{v}) = {} expected {expected_r:.2}",
                crop[i]
            );
            assert!(
                (crop[i + 1] as f64 - expected_g).abs() <= 1.0,
                "G({u},{v}) = {} expected {expected_g:.2}",
                crop[i + 1]
            );
            assert_eq!(crop[i + 2], 77);
        }
    }
}

#[test]
fn test_crop_pad_context_matches_upstream_golden_fixture() {
    let rgb = synthetic_frame();
    let cases: [(&str, BoundingBox, f32, &[u8]); 3] = [
        (
            "golden_scale_2_7",
            BoundingBox::new(60.0, 38.0, 96.5, 81.0),
            2.7,
            include_bytes!("fixtures/pad_crop/golden_scale_2_7.rgb"),
        ),
        (
            "golden_scale_4_0_edge",
            BoundingBox::new(118.0, 70.0, 142.0, 101.0),
            4.0,
            include_bytes!("fixtures/pad_crop/golden_scale_4_0_edge.rgb"),
        ),
        (
            "golden_scale_2_7_upscale",
            BoundingBox::new(20.25, 20.0, 30.5, 32.0),
            2.7,
            include_bytes!("fixtures/pad_crop/golden_scale_2_7_upscale.rgb"),
        ),
    ];
    for (name, bbox, scale, golden) in cases {
        assert_eq!(golden.len(), 80 * 80 * 3, "{name}: fixture size");
        let crop = crop_pad_context(&rgb, FRAME_W, FRAME_H, &bbox, scale, 80, 80).expect(name);
        assert_within_one_lsb(name, &crop, golden);
    }
}

#[test]
fn test_crop_pad_context_golden_windows_match_generator_report() {
    // Windows printed by generate_golden.py for the three fixture cases.
    let cases = [
        (
            BoundingBox::new(60.0, 38.0, 96.5, 81.0),
            2.7,
            PadCropWindow {
                x: 28,
                y: 1,
                width: 100,
                height: 117,
            },
        ),
        (
            BoundingBox::new(118.0, 70.0, 142.0, 101.0),
            4.0,
            PadCropWindow {
                x: 66,
                y: 0,
                width: 94,
                height: 120,
            },
        ),
        (
            BoundingBox::new(20.25, 20.0, 30.5, 32.0),
            2.7,
            PadCropWindow {
                x: 11,
                y: 9,
                width: 29,
                height: 34,
            },
        ),
    ];
    for (bbox, scale, expected) in cases {
        assert_eq!(
            pad_crop_window(&bbox, scale, FRAME_W, FRAME_H),
            Some(expected),
            "{bbox:?} @ {scale}"
        );
    }
}

#[test]
fn test_crop_pad_context_degenerate_box_yields_black_crop() {
    let rgb = synthetic_frame();
    let crop = crop_pad_context(
        &rgb,
        FRAME_W,
        FRAME_H,
        &BoundingBox::new(50.0, 50.0, 50.0, 50.0),
        2.7,
        80,
        80,
    )
    .expect("degenerate box is not a buffer error");
    assert_eq!(crop.len(), 80 * 80 * 3);
    assert!(crop.iter().all(|&b| b == 0), "fail-closed black crop");
}

#[test]
fn test_crop_pad_context_validates_buffers_and_dimensions() {
    let rgb = synthetic_frame();
    let bbox = BoundingBox::new(60.0, 38.0, 96.5, 81.0);
    assert!(matches!(
        crop_pad_context(&rgb, 0, FRAME_H, &bbox, 2.7, 80, 80),
        Err(VisionError::InvalidDimensions { .. })
    ));
    assert!(matches!(
        crop_pad_context(&rgb, FRAME_W, FRAME_H, &bbox, 2.7, 0, 80),
        Err(VisionError::InvalidDimensions { .. })
    ));
    assert!(matches!(
        crop_pad_context(&rgb[..10], FRAME_W, FRAME_H, &bbox, 2.7, 80, 80),
        Err(VisionError::InvalidBufferSize { .. })
    ));
}
