//! Contract tests for the PAM stack position chosen by `soos-admin gdm enable`
//! (review finding STO-03, GitHub #177).
//!
//! Fixtures reproduce the `gdm-password` service and the shared auth stacks it
//! delegates to as shipped by Ubuntu 24.04 (`gdm3`), Fedora 40 (`gdm` +
//! `authselect local with-faillock`) and Arch Linux (`gdm` + `pambase`).
//! The invariant under test: a facial success can never skip a lockout, nologin,
//! shell or user-filter gate (`pam_faillock.so preauth`, `pam_nologin.so`,
//! `pam_shells.so`, `pam_succeed_if.so`) that the original stack runs before the
//! first credential module.

#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::indexing_slicing,
    clippy::arithmetic_side_effects,
    reason = "Contractual test suite uses direct assertions and unwrap"
)]

use soos_admin_cli::args::GdmAction;
use soos_admin_cli::gdm::{
    configure_gdm, find_pam_module, get_gdm_status, pam_backup_path, GDM_BLOCK_BEGIN,
    GDM_BLOCK_END, GDM_PAM_LINE, LEGACY_GDM_PAM_LINE, PAM_MODULE_FILE,
};
use std::fs;
use std::path::{Path, PathBuf};
use tempfile::tempdir;

// ----------------------------------------------------------------------------
// Distribution fixtures
// ----------------------------------------------------------------------------

/// `/etc/pam.d/gdm-password` from Ubuntu 24.04 (`gdm3` 46).
const UBUNTU_GDM_PASSWORD: &str = "\
#%PAM-1.0
auth    requisite       pam_nologin.so
auth\trequired\tpam_succeed_if.so user != root quiet_success
@include common-auth
auth    optional        pam_gnome_keyring.so
@include common-account
# SELinux needs to be the first session rule. This ensures that any
# lingering context has been cleared. Without this it is possible
# that a module would execute code in the wrong domain.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so close
session required        pam_loginuid.so
# SELinux needs to intervene at login time to ensure that the process
# starts in the proper default security context. Only sessions which are
# intended to run in the user's context should be run after this.
session [success=ok ignore=ignore module_unknown=ignore default=bad]        pam_selinux.so open
session optional        pam_keyinit.so force revoke
session required        pam_limits.so
session required        pam_env.so readenv=1
session required        pam_env.so readenv=1 user_readenv=1 envfile=/etc/default/locale
@include common-session
session optional        pam_gnome_keyring.so auto_start
@include common-password
";

/// Stock Ubuntu 24.04 `/etc/pam.d/common-auth` (no faillock).
const UBUNTU_COMMON_AUTH: &str = "\
# /etc/pam.d/common-auth - authentication settings common to all services
#
# here are the per-package modules (the \"Primary\" block)
auth\t[success=1 default=ignore]\tpam_unix.so nullok
# here's the fallback if no module succeeds
auth\trequisite\t\t\tpam_deny.so
# prime the stack with a positive return value if there isn't one already;
auth\trequired\t\t\tpam_permit.so
# and here are more per-package modules (the \"Additional\" block)
auth\toptional\t\t\tpam_cap.so
# end of pam-auth-update config
";

/// Ubuntu 24.04 `/etc/pam.d/common-auth` with the `faillock` pam-auth-update profile.
const UBUNTU_COMMON_AUTH_FAILLOCK: &str = "\
# /etc/pam.d/common-auth - authentication settings common to all services
auth\trequisite\t\t\tpam_faillock.so preauth
auth\t[success=1 default=ignore]\tpam_unix.so nullok
auth\t[default=die]\t\t\tpam_faillock.so authfail
auth\trequisite\t\t\tpam_deny.so
auth\trequired\t\t\tpam_permit.so
auth\tsufficient\t\t\tpam_faillock.so authsucc
auth\toptional\t\t\tpam_cap.so
";

/// `/etc/pam.d/gdm-password` from Fedora 40 (`gdm` 46).
const FEDORA_GDM_PASSWORD: &str = "\
auth     [success=done ignore=ignore default=bad] pam_selinux_permit.so
auth        substack      password-auth
auth        optional      pam_gnome_keyring.so
auth        include       postlogin

account     required      pam_nologin.so
account     include       password-auth

password    substack       password-auth
-password   optional       pam_gnome_keyring.so use_authtok

session     required      pam_selinux.so close
session     required      pam_loginuid.so
session     required      pam_selinux.so open
session     optional      pam_keyinit.so force revoke
session     required      pam_namespace.so
session     include       password-auth
session     optional      pam_gnome_keyring.so auto_start
session     include       postlogin
";

/// Fedora 40 `/etc/pam.d/password-auth` generated by `authselect select local with-faillock`.
const FEDORA_PASSWORD_AUTH: &str = "\
# Generated by authselect
# Do not modify this file manually, use authselect instead. Any user changes will be overwritten.
# You can stop authselect from managing your configuration by calling 'authselect opt-out'.
# See authselect(8) for more details.

auth        required                                     pam_env.so
auth        required                                     pam_faillock.so preauth silent
auth        sufficient                                   pam_unix.so nullok
auth        required                                     pam_faillock.so authfail
auth        required                                     pam_deny.so

account     required                                     pam_faillock.so
account     required                                     pam_unix.so

password    requisite                                    pam_pwquality.so
password    sufficient                                   pam_unix.so yescrypt shadow nullok use_authtok
password    required                                     pam_deny.so

session     optional                                     pam_keyinit.so revoke
session     required                                     pam_limits.so
session     required                                     pam_unix.so
";

/// Fedora 40 `/etc/pam.d/postlogin`.
const FEDORA_POSTLOGIN: &str = "\
# Generated by authselect
session     optional                   pam_umask.so silent
session     [success=1 default=ignore] pam_succeed_if.so service !~ gdm* service !~ su* quiet
session     [default=1]                pam_lastlog.so nowtmp showfailed
session     optional                   pam_lastlog.so silent noupdate showfailed
";

/// `/etc/pam.d/gdm-password` from Arch Linux (`gdm` 46).
const ARCH_GDM_PASSWORD: &str = "\
#%PAM-1.0

auth       include                     system-local-login
auth       optional                    pam_gnome_keyring.so
account    include                     system-local-login
password   include                     system-local-login
password   optional                    pam_gnome_keyring.so use_authtok
session    include                     system-local-login
session    optional                    pam_gnome_keyring.so auto_start
";

/// Arch Linux `pambase` `/etc/pam.d/system-local-login`.
const ARCH_SYSTEM_LOCAL_LOGIN: &str = "\
#%PAM-1.0

auth      include   system-login
account   include   system-login
password  include   system-login
session   include   system-login
";

/// Arch Linux `pambase` `/etc/pam.d/system-login`.
const ARCH_SYSTEM_LOGIN: &str = "\
#%PAM-1.0

auth       required   pam_shells.so
auth       requisite  pam_nologin.so
auth       include    system-auth

account    required   pam_access.so
account    required   pam_nologin.so
account    include    system-auth

password   include    system-auth

session    optional   pam_loginuid.so
session    optional   pam_keyinit.so       force revoke
session    include    system-auth
session    optional   pam_motd.so
-session   optional   pam_systemd.so
session    required   pam_env.so
";

/// Arch Linux `pambase` `/etc/pam.d/system-auth`.
const ARCH_SYSTEM_AUTH: &str = "\
#%PAM-1.0

auth       required                    pam_faillock.so      preauth
# Optionally use requisite above if you do not want to prompt for the password
# on locked accounts.
-auth      [success=2 default=ignore]  pam_systemd_home.so
auth       [success=1 default=bad]     pam_unix.so          try_first_pass nullok
auth       [default=die]               pam_faillock.so      authfail
auth       optional                    pam_permit.so
auth       required                    pam_env.so
auth       required                    pam_faillock.so      authsucc
# If you drop the above call to pam_faillock.so the lock will be done also
# on non-consecutive authentication failures.

-account   [success=1 default=ignore]  pam_systemd_home.so
account    required                    pam_unix.so
account    optional                    pam_permit.so
account    required                    pam_time.so

-password  [success=1 default=ignore]  pam_systemd_home.so
password   required                    pam_unix.so          try_first_pass nullok shadow
password   optional                    pam_permit.so

-session   optional                    pam_systemd_home.so
session    required                    pam_limits.so
session    required                    pam_unix.so
session    optional                    pam_permit.so
";

/// A self-contained GDM service carrying its own faillock stack (no delegation).
const INLINE_FAILLOCK_GDM_PASSWORD: &str = "\
#%PAM-1.0
auth        required      pam_env.so
auth        required      pam_faillock.so preauth silent deny=5
auth        sufficient    pam_unix.so nullok
auth        required      pam_faillock.so authfail
auth        required      pam_deny.so
account     required      pam_faillock.so
account     required      pam_unix.so
";

// ----------------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------------

struct Fixture {
    _dir: tempfile::TempDir,
    pam_dir: PathBuf,
    pam_file: PathBuf,
    disable_file: PathBuf,
}

fn fixture(gdm_password: &str, shared: &[(&str, &str)]) -> Fixture {
    let dir = tempdir().unwrap();
    let pam_dir = dir.path().join("pam.d");
    fs::create_dir(&pam_dir).unwrap();
    for (name, content) in shared {
        fs::write(pam_dir.join(name), content).unwrap();
    }
    let pam_file = pam_dir.join("gdm-password");
    fs::write(&pam_file, gdm_password).unwrap();
    let disable_file = dir.path().join("soos").join("gdm.disable");
    Fixture {
        _dir: dir,
        pam_dir,
        pam_file,
        disable_file,
    }
}

fn enable(f: &Fixture) -> String {
    configure_gdm(&GdmAction::Enable, &f.pam_file, &f.disable_file).expect("enable must succeed");
    fs::read_to_string(&f.pam_file).unwrap()
}

/// Returns `(type, control, module, args)` for an active PAM rule line.
fn parse_rule(line: &str) -> Option<(String, String, String, String)> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    if let Some(rest) = line.strip_prefix("@include") {
        return Some((
            "@include".into(),
            "include".into(),
            rest.trim().into(),
            String::new(),
        ));
    }
    let (kind, rest) = line.split_once(char::is_whitespace)?;
    let rest = rest.trim_start();
    let (control, rest) = if rest.starts_with('[') {
        let end = rest.find(']')?;
        (rest[..=end].to_string(), rest[end + 1..].trim_start())
    } else {
        let (c, r) = rest.split_once(char::is_whitespace)?;
        (c.to_string(), r.trim_start())
    };
    let (module, args) = match rest.split_once(char::is_whitespace) {
        Some((m, a)) => (m.to_string(), a.trim().to_string()),
        None => (rest.to_string(), String::new()),
    };
    Some((kind.to_string(), control, module, args))
}

/// Flattens the `auth` phase as Linux-PAM would evaluate it, expanding
/// `include`, `substack` and `@include` from `pam_dir`. Returns
/// `"module args"` strings in evaluation order.
fn flatten_auth(pam_dir: &Path, content: &str, depth: usize) -> Vec<String> {
    assert!(depth < 8, "include loop in fixture");
    let mut out = Vec::new();
    for line in content.lines() {
        let Some((kind, control, module, args)) = parse_rule(line) else {
            continue;
        };
        let is_auth = kind == "auth" || kind == "-auth" || kind == "@include";
        if !is_auth {
            continue;
        }
        if kind == "@include" || control == "include" || control == "substack" {
            if let Ok(sub) = fs::read_to_string(pam_dir.join(&module)) {
                out.extend(flatten_auth(pam_dir, &sub, depth + 1));
            }
            continue;
        }
        out.push(format!("{module} {args}").trim().to_string());
    }
    out
}

fn first_index(stack: &[String], needle: &str) -> Option<usize> {
    stack.iter().position(|m| m.contains(needle))
}

fn line_index(content: &str, needle: &str) -> usize {
    content
        .lines()
        .position(|l| l.contains(needle))
        .unwrap_or_else(|| panic!("line containing {needle:?} not found in:\n{content}"))
}

/// Asserts that, in the flattened auth stack, `pam_soos.so` runs after every
/// listed gate and before the first credential module.
fn assert_soos_after_gates(f: &Fixture, gates: &[&str], credential: &str) {
    let content = fs::read_to_string(&f.pam_file).unwrap();
    let stack = flatten_auth(&f.pam_dir, &content, 0);
    let soos = first_index(&stack, "pam_soos.so").expect("pam_soos.so in the auth stack");
    for gate in gates {
        let gate_at = first_index(&stack, gate)
            .unwrap_or_else(|| panic!("gate {gate:?} missing from stack {stack:#?}"));
        assert!(
            gate_at < soos,
            "{gate:?} (#{gate_at}) must run before pam_soos.so (#{soos}): {stack:#?}"
        );
    }
    let cred = first_index(&stack, credential).expect("credential module in stack");
    assert!(
        soos < cred,
        "pam_soos.so (#{soos}) must run before {credential:?} (#{cred}): {stack:#?}"
    );
}

// ----------------------------------------------------------------------------
// Ubuntu 24.04
// ----------------------------------------------------------------------------

#[test]
fn test_gdm_enable_ubuntu_inserts_after_nologin_and_succeed_if_before_common_auth() {
    let f = fixture(UBUNTU_GDM_PASSWORD, &[("common-auth", UBUNTU_COMMON_AUTH)]);
    let content = enable(&f);

    let soos = line_index(&content, "pam_soos.so");
    assert!(line_index(&content, "pam_nologin.so") < soos);
    assert!(line_index(&content, "pam_succeed_if.so") < soos);
    assert_eq!(
        soos + 2,
        line_index(&content, "@include common-auth"),
        "the managed block ends right before '@include common-auth'"
    );
    assert_eq!(
        content.lines().nth(soos).unwrap(),
        GDM_PAM_LINE,
        "the inserted rule is exactly GDM_PAM_LINE"
    );
    assert!(
        !content.contains("pam_faillock.so"),
        "no faillock guard when the delegated stack has no faillock"
    );
    assert_soos_after_gates(&f, &["pam_nologin.so", "pam_succeed_if.so"], "pam_unix.so");

    // Every original line is preserved verbatim and in order.
    let without_block: Vec<&str> = content
        .lines()
        .filter(|l| *l != GDM_BLOCK_BEGIN && *l != GDM_BLOCK_END && *l != GDM_PAM_LINE)
        .collect();
    assert_eq!(
        without_block,
        UBUNTU_GDM_PASSWORD.lines().collect::<Vec<_>>()
    );
}

#[test]
fn test_gdm_enable_ubuntu_faillock_profile_adds_preauth_guard_before_soos() {
    let f = fixture(
        UBUNTU_GDM_PASSWORD,
        &[("common-auth", UBUNTU_COMMON_AUTH_FAILLOCK)],
    );
    let content = enable(&f);

    let soos = line_index(&content, "pam_soos.so");
    let guard = line_index(&content, "pam_faillock.so preauth");
    assert!(
        guard < soos,
        "faillock preauth guard must precede pam_soos.so:\n{content}"
    );
    assert!(line_index(&content, GDM_BLOCK_BEGIN) < guard);
    assert!(soos < line_index(&content, "@include common-auth"));
    assert_eq!(
        content.lines().nth(guard).unwrap(),
        "auth  requisite  pam_faillock.so preauth",
        "the guard copies the control and arguments of the delegated preauth rule"
    );
    assert_soos_after_gates(
        &f,
        &[
            "pam_nologin.so",
            "pam_succeed_if.so",
            "pam_faillock.so preauth",
        ],
        "pam_unix.so",
    );
}

// ----------------------------------------------------------------------------
// Fedora 40
// ----------------------------------------------------------------------------

#[test]
fn test_gdm_enable_fedora_never_inserts_at_top_and_guards_faillock_preauth() {
    let f = fixture(
        FEDORA_GDM_PASSWORD,
        &[
            ("password-auth", FEDORA_PASSWORD_AUTH),
            ("postlogin", FEDORA_POSTLOGIN),
        ],
    );
    let content = enable(&f);

    let first = content.lines().next().unwrap();
    assert!(
        first.contains("pam_selinux_permit.so"),
        "the first rule stays first (pam_soos.so is never inserted at index 0): {first}"
    );
    let soos = line_index(&content, "pam_soos.so");
    assert!(line_index(&content, "pam_selinux_permit.so") < soos);
    assert!(soos < line_index(&content, "substack      password-auth"));
    assert_eq!(
        content
            .lines()
            .nth(line_index(&content, "pam_faillock.so"))
            .unwrap(),
        "auth  required  pam_faillock.so preauth silent"
    );
    assert_soos_after_gates(
        &f,
        &["pam_selinux_permit.so", "pam_faillock.so preauth"],
        "pam_unix.so",
    );
    // The account phase (pam_nologin, pam_faillock account) is untouched.
    assert!(content.contains("account     required      pam_nologin.so\n"));
}

// ----------------------------------------------------------------------------
// Arch Linux
// ----------------------------------------------------------------------------

#[test]
fn test_gdm_enable_arch_guards_shells_nologin_and_faillock_from_nested_includes() {
    let f = fixture(
        ARCH_GDM_PASSWORD,
        &[
            ("system-local-login", ARCH_SYSTEM_LOCAL_LOGIN),
            ("system-login", ARCH_SYSTEM_LOGIN),
            ("system-auth", ARCH_SYSTEM_AUTH),
        ],
    );
    let content = enable(&f);

    let soos = line_index(&content, "pam_soos.so");
    let shells = line_index(&content, "pam_shells.so");
    let nologin = line_index(&content, "pam_nologin.so");
    let faillock = line_index(&content, "pam_faillock.so preauth");
    assert!(
        shells < nologin && nologin < faillock && faillock < soos,
        "guards keep the original evaluation order before pam_soos.so:\n{content}"
    );
    assert!(
        soos < line_index(
            &content,
            "auth       include                     system-local-login"
        )
    );
    assert_soos_after_gates(
        &f,
        &["pam_shells.so", "pam_nologin.so", "pam_faillock.so preauth"],
        "pam_unix.so",
    );
    // Rules after the first credential module (authfail, authsucc) are never copied.
    assert!(!content.contains("authfail"));
    assert!(!content.contains("authsucc"));
}

// ----------------------------------------------------------------------------
// Self-contained stacks
// ----------------------------------------------------------------------------

#[test]
fn test_gdm_enable_inline_faillock_inserts_after_preauth_before_pam_unix() {
    let f = fixture(INLINE_FAILLOCK_GDM_PASSWORD, &[]);
    let content = enable(&f);

    let soos = line_index(&content, "pam_soos.so");
    assert!(line_index(&content, "pam_faillock.so preauth") < soos);
    assert!(soos < line_index(&content, "pam_unix.so nullok"));
    assert_eq!(
        content.matches("pam_faillock.so preauth").count(),
        1,
        "an in-file preauth already precedes the insertion point: no duplicate guard"
    );
    assert_soos_after_gates(&f, &["pam_faillock.so preauth"], "pam_unix.so");
}

#[test]
fn test_gdm_enable_refuses_a_stack_without_a_credential_anchor() {
    let original = "#%PAM-1.0\nauth required pam_env.so\naccount required pam_unix.so\n";
    let f = fixture(original, &[]);
    let result = configure_gdm(&GdmAction::Enable, &f.pam_file, &f.disable_file);
    assert!(result.is_err(), "no anchor: refuse instead of guessing");
    assert_eq!(fs::read_to_string(&f.pam_file).unwrap(), original);
    assert!(
        !pam_backup_path(&f.pam_file).exists(),
        "no backup on refusal"
    );
}

#[test]
fn test_gdm_enable_refuses_when_a_jump_crosses_the_insertion_point() {
    let original = "\
#%PAM-1.0
auth [success=1 default=ignore] pam_succeed_if.so user ingroup nopasswdlogin
auth sufficient pam_unix.so nullok
auth required pam_deny.so
";
    let f = fixture(original, &[]);
    let result = configure_gdm(&GdmAction::Enable, &f.pam_file, &f.disable_file);
    assert!(
        result.is_err(),
        "inserting would silently change the target of success=1"
    );
    assert_eq!(fs::read_to_string(&f.pam_file).unwrap(), original);
    assert!(!pam_backup_path(&f.pam_file).exists());
}

#[test]
fn test_gdm_enable_refuses_non_utf8_pam_file() {
    let dir = tempdir().unwrap();
    let pam_file = dir.path().join("gdm-password");
    let original: &[u8] = b"#%PAM-1.0\nauth required pam_env.so \xff\n@include common-auth\n";
    fs::write(&pam_file, original).unwrap();
    let result = configure_gdm(
        &GdmAction::Enable,
        &pam_file,
        &dir.path().join("gdm.disable"),
    );
    assert!(
        result.is_err(),
        "non UTF-8 bytes are never rewritten lossily"
    );
    assert_eq!(fs::read(&pam_file).unwrap(), original);
}

// ----------------------------------------------------------------------------
// Legacy migration and idempotency
// ----------------------------------------------------------------------------

#[test]
fn test_gdm_enable_migrates_a_misplaced_legacy_line() {
    // What the pre-#177 implementation produced on Fedora: the legacy line at index 0.
    let legacy = format!("{LEGACY_GDM_PAM_LINE}\n{FEDORA_GDM_PASSWORD}");
    let f = fixture(
        &legacy,
        &[
            ("password-auth", FEDORA_PASSWORD_AUTH),
            ("postlogin", FEDORA_POSTLOGIN),
        ],
    );
    let content = enable(&f);

    assert!(
        !content.contains(LEGACY_GDM_PAM_LINE),
        "legacy line removed"
    );
    assert_eq!(content.matches("pam_soos.so").count(), 1);
    assert!(content
        .lines()
        .next()
        .unwrap()
        .contains("pam_selinux_permit.so"));
    assert_soos_after_gates(
        &f,
        &["pam_selinux_permit.so", "pam_faillock.so preauth"],
        "pam_unix.so",
    );
    assert_eq!(
        fs::read_to_string(pam_backup_path(&f.pam_file)).unwrap(),
        FEDORA_GDM_PASSWORD,
        "the backup holds the stack without any soos rule"
    );
}

#[test]
fn test_gdm_enable_is_idempotent_on_distribution_stacks() {
    let f = fixture(
        ARCH_GDM_PASSWORD,
        &[
            ("system-local-login", ARCH_SYSTEM_LOCAL_LOGIN),
            ("system-login", ARCH_SYSTEM_LOGIN),
            ("system-auth", ARCH_SYSTEM_AUTH),
        ],
    );
    let first = enable(&f);
    let second = enable(&f);
    assert_eq!(first, second, "second enable is a no-op");
    assert_eq!(second.matches(GDM_BLOCK_BEGIN).count(), 1);
    assert_eq!(second.matches("pam_soos.so").count(), 1);
}

#[test]
fn test_gdm_enable_leaves_an_admin_managed_soos_rule_untouched() {
    let original = "\
#%PAM-1.0
auth requisite pam_nologin.so
auth [success=done default=ignore] pam_soos.so timeout_ms=1500
@include common-auth
";
    let f = fixture(original, &[]);
    let content = enable(&f);
    assert_eq!(
        content, original,
        "a rule written by the administrator is kept"
    );
}

// ----------------------------------------------------------------------------
// Restore
// ----------------------------------------------------------------------------

#[test]
fn test_gdm_restore_puts_back_the_pristine_file_and_removes_the_backup() {
    use std::os::unix::fs::PermissionsExt;
    let f = fixture(
        FEDORA_GDM_PASSWORD,
        &[
            ("password-auth", FEDORA_PASSWORD_AUTH),
            ("postlogin", FEDORA_POSTLOGIN),
        ],
    );
    fs::set_permissions(&f.pam_file, fs::Permissions::from_mode(0o644)).unwrap();
    enable(&f);

    let status = configure_gdm(&GdmAction::Restore, &f.pam_file, &f.disable_file)
        .expect("restore must succeed");
    assert!(!status.installed, "pam_soos.so is gone after restore");
    assert_eq!(
        fs::read_to_string(&f.pam_file).unwrap(),
        FEDORA_GDM_PASSWORD
    );
    assert_eq!(
        fs::metadata(&f.pam_file).unwrap().permissions().mode() & 0o7777,
        0o644
    );
    assert!(!pam_backup_path(&f.pam_file).exists(), "backup consumed");
    let leftovers: Vec<String> = fs::read_dir(&f.pam_dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with('.'))
        .collect();
    assert!(
        leftovers.is_empty(),
        "no temporary file left: {leftovers:?}"
    );
}

#[test]
fn test_gdm_restore_without_backup_fails_and_changes_nothing() {
    let f = fixture(UBUNTU_GDM_PASSWORD, &[]);
    let result = configure_gdm(&GdmAction::Restore, &f.pam_file, &f.disable_file);
    assert!(result.is_err(), "nothing to restore");
    assert_eq!(
        fs::read_to_string(&f.pam_file).unwrap(),
        UBUNTU_GDM_PASSWORD
    );
    let status = get_gdm_status(&f.pam_file, &f.disable_file);
    assert!(!status.installed);
}

#[test]
fn test_gdm_restore_refuses_a_symlinked_backup() {
    let f = fixture(UBUNTU_GDM_PASSWORD, &[]);
    let elsewhere = f.pam_dir.join("attacker-controlled");
    fs::write(&elsewhere, "auth sufficient pam_permit.so\n").unwrap();
    std::os::unix::fs::symlink(&elsewhere, pam_backup_path(&f.pam_file)).unwrap();
    let result = configure_gdm(&GdmAction::Restore, &f.pam_file, &f.disable_file);
    assert!(result.is_err(), "a symlinked backup is never trusted");
    assert_eq!(
        fs::read_to_string(&f.pam_file).unwrap(),
        UBUNTU_GDM_PASSWORD
    );
}

// ----------------------------------------------------------------------------
// Installed module check
// ----------------------------------------------------------------------------

#[test]
fn test_find_pam_module_locates_the_installed_module() {
    let dir = tempdir().unwrap();
    let empty = dir.path().join("lib64-security");
    let security = dir.path().join("lib-security");
    fs::create_dir(&empty).unwrap();
    fs::create_dir(&security).unwrap();
    fs::write(security.join(PAM_MODULE_FILE), b"\x7fELF").unwrap();

    assert_eq!(
        find_pam_module(&[empty.clone(), security.clone()]),
        Some(security.join(PAM_MODULE_FILE))
    );
    assert_eq!(find_pam_module(&[empty]), None, "module absent");
    assert_eq!(find_pam_module(&[]), None);
}

#[test]
fn test_find_pam_module_ignores_directories_named_like_the_module() {
    let dir = tempdir().unwrap();
    fs::create_dir(dir.path().join(PAM_MODULE_FILE)).unwrap();
    assert_eq!(find_pam_module(&[dir.path().to_path_buf()]), None);
}

/// End to end through the `soos-admin` binary: `gdm enable` refuses to edit the PAM
/// file while `pam_soos.so` is not installed, and succeeds once it is.
#[test]
fn test_soos_admin_gdm_enable_refuses_when_module_is_not_installed() {
    let f = fixture(UBUNTU_GDM_PASSWORD, &[("common-auth", UBUNTU_COMMON_AUTH)]);
    let modules = f.pam_dir.parent().unwrap().join("security");
    fs::create_dir(&modules).unwrap();
    let run = || {
        std::process::Command::new(env!("CARGO_BIN_EXE_soos-admin"))
            .args(["gdm", "enable", "--pam-file"])
            .arg(&f.pam_file)
            .arg("--disable-file")
            .arg(&f.disable_file)
            .arg("--pam-module-dir")
            .arg(&modules)
            .output()
            .unwrap()
    };

    let refused = run();
    assert!(!refused.status.success(), "missing module must be refused");
    assert!(String::from_utf8_lossy(&refused.stderr).contains("pam_soos.so not found"));
    assert_eq!(
        fs::read_to_string(&f.pam_file).unwrap(),
        UBUNTU_GDM_PASSWORD
    );
    assert!(!pam_backup_path(&f.pam_file).exists());

    fs::write(modules.join(PAM_MODULE_FILE), b"\x7fELF").unwrap();
    let accepted = run();
    assert!(
        accepted.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&accepted.stderr)
    );
    assert!(fs::read_to_string(&f.pam_file)
        .unwrap()
        .contains(GDM_PAM_LINE));
}

// ----------------------------------------------------------------------------
// Anchor classification (candid review 2026-09-30, Finding 1)
// ----------------------------------------------------------------------------

/// Runs `enable` expecting a refusal; asserts the error names `module`, the PAM file
/// is byte-for-byte unchanged, no backup exists and the disable flag is kept.
fn assert_enable_refused(f: &Fixture, original: &str, module: &str) {
    fs::create_dir_all(f.disable_file.parent().unwrap()).unwrap();
    fs::write(&f.disable_file, "disabled\n").unwrap();
    let err = configure_gdm(&GdmAction::Enable, &f.pam_file, &f.disable_file)
        .expect_err("enable must refuse an unclassified auth rule before the credential anchor");
    let message = err.to_string();
    assert!(
        message.contains(module),
        "the error must name the offending module {module:?}: {message}"
    );
    assert_eq!(fs::read_to_string(&f.pam_file).unwrap(), original);
    assert!(
        !pam_backup_path(&f.pam_file).exists(),
        "no backup on refusal"
    );
    assert!(f.disable_file.exists(), "the disable flag stays in place");
    let leftovers: Vec<String> = fs::read_dir(&f.pam_dir)
        .unwrap()
        .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
        .filter(|n| n.starts_with('.'))
        .collect();
    assert!(leftovers.is_empty(), "no temporary file: {leftovers:?}");
}

/// Reviewer scenario (a): a lockout module unknown to soos precedes the shared stack.
/// The old anchor logic wrote the managed block at index 0, before `pam_tally2`.
#[test]
fn test_gdm_enable_refuses_unclassified_lockout_module_before_include() {
    let original = "\
#%PAM-1.0
auth required pam_tally2.so deny=5 onerr=fail
@include common-auth
@include common-account
";
    let f = fixture(original, &[("common-auth", UBUNTU_COMMON_AUTH)]);
    assert_enable_refused(&f, original, "pam_tally2.so");
}

/// Reviewer scenario (b): an unclassified `optional` module sits between the in-file
/// gates and the shared stack that runs `pam_faillock.so preauth`. The old anchor
/// logic placed soos before `pam_group` and never copied the faillock gate.
#[test]
fn test_gdm_enable_refuses_unclassified_module_before_include_with_faillock() {
    let original = "\
#%PAM-1.0
auth requisite pam_nologin.so
auth optional pam_group.so
@include common-auth
";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth required pam_faillock.so preauth\nauth [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\nauth required pam_permit.so\n",
        )],
    );
    assert_enable_refused(&f, original, "pam_group.so");
}

/// An unclassified rule directly in front of `pam_unix.so` is refused as well.
#[test]
fn test_gdm_enable_refuses_unclassified_module_before_inline_credential() {
    let original = "\
#%PAM-1.0
auth required pam_env.so
auth required pam_faildelay.so delay=2000000
auth required pam_mystery_lockout.so
auth sufficient pam_unix.so nullok
auth required pam_deny.so
";
    let f = fixture(original, &[]);
    assert_enable_refused(&f, original, "pam_mystery_lockout.so");
}

/// An unclassified rule inside the delegated stack, before its credential module,
/// makes the gates of that stack unknowable: refuse.
#[test]
fn test_gdm_enable_refuses_unclassified_module_inside_delegated_stack() {
    let original = "#%PAM-1.0\nauth requisite pam_nologin.so\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth required pam_faillock.so preauth\nauth required pam_tally2.so deny=5\nauth [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\n",
        )],
    );
    assert_enable_refused(&f, original, "pam_tally2.so");
}

/// A conditional (jump) gate inside the delegated stack cannot be copied in front of
/// soos without changing its meaning: refuse instead of skipping it.
#[test]
fn test_gdm_enable_refuses_conditional_gate_inside_delegated_stack() {
    let original = "#%PAM-1.0\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth [success=1 default=ignore] pam_succeed_if.so user ingroup nopasswdlogin\nauth sufficient pam_unix.so nullok\nauth requisite pam_deny.so\n",
        )],
    );
    assert_enable_refused(&f, original, "pam_succeed_if.so");
}

/// An include target that cannot be resolved inside the PAM directory (absolute
/// path) hides its gates: refuse.
#[test]
fn test_gdm_enable_refuses_an_unresolvable_include_target() {
    let original = "#%PAM-1.0\nauth include /etc/pam.d/common-auth\n";
    let f = fixture(original, &[]);
    assert_enable_refused(&f, original, "/etc/pam.d/common-auth");
}

/// When the delegated stack ends without a credential module, the rules following
/// the delegation in the edited file are scanned too: an unclassified one is refused,
/// gates are copied and a later credential module ends the scan.
#[test]
fn test_gdm_enable_scans_past_a_gate_only_include() {
    let refused = "\
#%PAM-1.0
@include common-gates
auth required pam_tally2.so deny=5
auth sufficient pam_unix.so nullok
";
    let gates = "auth requisite pam_nologin.so\n";
    let f = fixture(refused, &[("common-gates", gates)]);
    assert_enable_refused(&f, refused, "pam_tally2.so");

    let accepted = "\
#%PAM-1.0
@include common-gates
auth required pam_shells.so
auth sufficient pam_unix.so nullok
auth required pam_deny.so
";
    let f = fixture(accepted, &[("common-gates", gates)]);
    let content = enable(&f);
    let soos = line_index(&content, "pam_soos.so");
    assert!(
        line_index(&content, "auth  requisite  pam_nologin.so") < soos,
        "the delegated nologin gate is copied:\n{content}"
    );
    assert!(
        line_index(&content, "auth  required  pam_shells.so") < soos,
        "the in-file gate after the delegation is copied:\n{content}"
    );
    assert!(soos < line_index(&content, "@include common-gates"));
    assert_soos_after_gates(&f, &["pam_nologin.so", "pam_shells.so"], "pam_unix.so");
}

/// Every documented credential module is a valid anchor, in the edited file and in a
/// delegated stack (after a copied faillock gate).
#[test]
fn test_gdm_enable_accepts_documented_credential_modules_as_anchor() {
    for module in [
        "pam_unix.so",
        "pam_sss.so",
        "pam_ldap.so",
        "pam_krb5.so",
        "pam_winbind.so",
        "pam_systemd_home.so",
        "pam_fprintd.so",
    ] {
        let inline = format!(
            "#%PAM-1.0\nauth requisite pam_nologin.so\nauth sufficient {module}\nauth required pam_deny.so\n"
        );
        let f = fixture(&inline, &[]);
        let content = enable(&f);
        let soos = line_index(&content, "pam_soos.so");
        assert!(line_index(&content, "pam_nologin.so") < soos, "{module}");
        assert!(
            soos < line_index(&content, &format!("auth sufficient {module}")),
            "{module}: soos must precede the credential module:\n{content}"
        );

        let shared = format!(
            "auth required pam_faillock.so preauth\nauth sufficient {module}\nauth required pam_deny.so\n"
        );
        let f = fixture(
            "#%PAM-1.0\n@include common-auth\n",
            &[("common-auth", &shared)],
        );
        let content = enable(&f);
        assert_soos_after_gates(&f, &["pam_faillock.so preauth"], module);
        assert!(content.contains("auth  required  pam_faillock.so preauth"));
    }
}

/// `restore` checks the size and type of the backup on the descriptor it reads from:
/// an oversized backup is refused and nothing changes.
#[test]
fn test_gdm_restore_refuses_an_oversized_backup() {
    let f = fixture(UBUNTU_GDM_PASSWORD, &[]);
    let backup = pam_backup_path(&f.pam_file);
    let oversized =
        vec![b'#'; usize::try_from(soos_admin_cli::gdm::MAX_PAM_FILE_BYTES).unwrap() + 1];
    fs::write(&backup, &oversized).unwrap();
    let result = configure_gdm(&GdmAction::Restore, &f.pam_file, &f.disable_file);
    assert!(result.is_err(), "an oversized backup is never restored");
    assert_eq!(
        fs::read_to_string(&f.pam_file).unwrap(),
        UBUNTU_GDM_PASSWORD
    );
    assert_eq!(fs::read(&backup).unwrap(), oversized, "backup kept");
}

// ----------------------------------------------------------------------------
// Candid review round 2 (2026-09-30)
// ----------------------------------------------------------------------------

/// Finding 2 (a): PAM type and control keywords are case-insensitive (pam.conf(5)).
/// A capitalized `Auth requisite pam_faillock.so preauth` in the delegated stack is a
/// gate that must be copied in front of soos.
#[test]
fn test_gdm_enable_copies_a_capitalized_delegated_gate() {
    let original = "#%PAM-1.0\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "Auth Requisite pam_faillock.so preauth\nAUTH [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\nauth required pam_permit.so\n",
        )],
    );
    let content = enable(&f);
    let soos = line_index(&content, "pam_soos.so");
    let gate = line_index(&content, "pam_faillock.so preauth");
    assert!(
        line_index(&content, GDM_BLOCK_BEGIN) < gate && gate < soos,
        "the capitalized preauth gate is copied before soos:\n{content}"
    );
    assert!(soos < line_index(&content, "@include common-auth"));
}

/// Finding 2 (b): a capitalized unclassified rule inside the delegated stack is still
/// an unclassified rule before the credential module: refuse.
#[test]
fn test_gdm_enable_refuses_a_capitalized_unclassified_delegated_rule() {
    let original = "#%PAM-1.0\nauth requisite pam_nologin.so\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "Auth required pam_tally2.so deny=5\nauth [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\n",
        )],
    );
    assert_enable_refused(&f, original, "pam_tally2.so");
}

/// Finding 2 (c): a capitalized `Auth [success=N ...]` jump in the edited file is part
/// of the jump check.
#[test]
fn test_gdm_enable_detects_a_capitalized_jump_before_the_insertion_point() {
    let original = "\
#%PAM-1.0
Auth [success=1 default=ignore] pam_succeed_if.so user ingroup nopasswdlogin
auth sufficient pam_unix.so nullok
auth required pam_deny.so
";
    let f = fixture(original, &[]);
    assert_enable_refused(&f, original, "jump");
}

/// Finding 2 (d): a capitalized `Include` delegates too; its unclassified rule refuses.
#[test]
fn test_gdm_enable_follows_a_capitalized_include_control() {
    let original = "#%PAM-1.0\nauth Include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth required pam_tally2.so deny=5\nauth sufficient pam_unix.so nullok\n",
        )],
    );
    assert_enable_refused(&f, original, "pam_tally2.so");
}

/// Finding 3 (a): an `optional pam_nologin.so` earlier in the file does not enforce
/// anything, so the delegated `requisite pam_nologin.so` gate is still copied.
#[test]
fn test_gdm_enable_copies_requisite_nologin_despite_an_earlier_optional_one() {
    let original = "#%PAM-1.0\nauth optional pam_nologin.so\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth requisite pam_nologin.so\nauth [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\nauth required pam_permit.so\n",
        )],
    );
    let content = enable(&f);
    let soos = line_index(&content, "pam_soos.so");
    let gate = line_index(&content, "auth  requisite  pam_nologin.so");
    assert!(
        line_index(&content, GDM_BLOCK_BEGIN) < gate && gate < soos,
        "the enforcing nologin gate is copied before soos:\n{content}"
    );
}

/// Finding 3 (b): the same for `optional` versus `required pam_faillock.so preauth`.
#[test]
fn test_gdm_enable_copies_required_preauth_despite_an_earlier_optional_one() {
    let original = "#%PAM-1.0\nauth optional pam_faillock.so preauth\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth required pam_faillock.so preauth\nauth [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\nauth required pam_permit.so\n",
        )],
    );
    let content = enable(&f);
    let soos = line_index(&content, "pam_soos.so");
    let gate = line_index(&content, "auth  required  pam_faillock.so preauth");
    assert!(
        line_index(&content, GDM_BLOCK_BEGIN) < gate && gate < soos,
        "the enforcing preauth gate is copied before soos:\n{content}"
    );
}

/// Finding 3 (c): an earlier plain `requisite` gate still counts as present, so it is
/// not copied twice.
#[test]
fn test_gdm_enable_does_not_duplicate_an_earlier_enforcing_gate() {
    let original = "#%PAM-1.0\nauth requisite pam_nologin.so\n@include common-auth\n";
    let f = fixture(
        original,
        &[(
            "common-auth",
            "auth requisite pam_nologin.so\nauth [success=1 default=ignore] pam_unix.so nullok\nauth requisite pam_deny.so\n",
        )],
    );
    let content = enable(&f);
    assert_eq!(
        content.matches("pam_nologin.so").count(),
        1,
        "an earlier enforcing gate is not duplicated:\n{content}"
    );
}

/// Round 2 Finding 1: a delegated stack missing from the PAM directory may be resolved
/// by libpam from a vendor directory (`/usr/lib/pam.d`) or make the stack fail; either
/// way soos cannot know its gates, so `enable` refuses.
#[test]
fn test_gdm_enable_refuses_a_missing_include_target() {
    let original = "#%PAM-1.0\nauth requisite pam_nologin.so\nauth include common-auth\n";
    let f = fixture(original, &[]);
    assert_enable_refused(&f, original, "common-auth");
}
